-- Generado por scripts/gen_seed.py desde lib/catalogo.ts — no editar a mano.
-- Re-generar con: python3 scripts/gen_seed.py

insert into empresas (id, nombre, corto, grupo) values
  ('adap', 'CLA ADAPTACIÓN', 'ADAP', 'Adapsys'),
  ('cons', 'CLA CONSULTORES', 'CONS', 'Adapsys'),
  ('clting', 'CLA CONSULTING', 'CLTG', 'Adapsys'),
  ('ctria', 'CLA CONSULTORIA', 'CTRIA', 'Adapsys'),
  ('sm', 'SANTA MARÍA', 'SM', 'Relacionadas');

insert into cuentas (id, empresa_id, nombre, moneda, tipo, saldo_inicial, principal) values
  ('a1', 'adap', 'CLA ADAPTACIÓN PESOS', 'CLP', 'banco', 199673281, true),
  ('a2', 'adap', 'CLA ADAPTACIÓN DÓLAR', 'USD', 'banco', 53, false),
  ('b1', 'cons', 'CLA CONSULTORES PESOS', 'CLP', 'banco', 4866278, true),
  ('b2', 'cons', 'CLA CONSULTORES DÓLAR', 'USD', 'banco', 4746, false),
  ('c1', 'clting', 'CLA CONSULTING PESOS', 'CLP', 'banco', 185642497, true),
  ('c2', 'clting', 'CLA CONSULTING DÓLAR', 'USD', 'banco', 21, false),
  ('d1', 'ctria', 'CLA CONSULTORIA PESOS', 'CLP', 'banco', 2731975, true),
  ('e1', 'sm', 'SANTA MARÍA PESOS', 'CLP', 'banco', -132518, true),
  ('e2', 'sm', 'SANTA MARÍA DÓLAR', 'USD', 'banco', 1000, false),
  ('x1', 'adap', 'Facturas por cobrar CLP', 'CLP', 'cxc', 0, false),
  ('x2', 'adap', 'Facturas por cobrar USD', 'USD', 'cxc', 16285, false);

insert into categorias (id, nombre, orden, controlado) values
  ('a-ingresos-clientes', 'A INGRESOS CLIENTES', 0, true),
  ('b-otros-ingresos', 'B OTROS INGRESOS', 1, true),
  ('1-costo-de-venta', '1 COSTO DE VENTA', 2, true),
  ('1-desarrollo-organizaciona', '1 DESARROLLO ORGANIZACIONAL', 3, true),
  ('2-gastos-administracion', '2 GASTOS ADMINISTRACIÓN', 4, true),
  ('2-0-comercial-y-marketing', '2.0 COMERCIAL Y MARKETING', 5, true),
  ('2-1-posicionamiento-nueva', '2.1 POSICIONAMIENTO NUEVA MARCA', 6, true),
  ('2-2-compra-activos', '2.2 COMPRA ACTIVOS', 7, true),
  ('2-3-gastos-sistemas-digita', '2.3 GASTOS SISTEMAS DIGITALES', 8, true),
  ('2-4-equipos-computacionale', '2.4 EQUIPOS COMPUTACIONALES', 9, true),
  ('3-recursos-humanos', '3 RECURSOS HUMANOS', 10, true),
  ('4-impuestos', '4 IMPUESTOS', 11, true),
  ('5-bancos', '5 BANCOS', 12, true),
  ('6-prestamos-bancarios', '6 PRESTAMOS BANCARIOS', 13, false),
  ('7-inversiones', '7 INVERSIONES', 14, false),
  ('8-relacionados-y-socios', '8 RELACIONADOS Y SOCIOS', 15, false);

insert into subcategorias (id, categoria_id, nombre, naturaleza, activa) values
  ('aasa', 'a-ingresos-clientes', 'AASA', 'ingreso', true),
  ('abastible', 'a-ingresos-clientes', 'ABASTIBLE', 'ingreso', true),
  ('acciona', 'a-ingresos-clientes', 'ACCIONA', 'ingreso', true),
  ('achs', 'a-ingresos-clientes', 'ACHS', 'ingreso', true),
  ('adapsys-australia', 'a-ingresos-clientes', 'ADAPSYS AUSTRALIA', 'ingreso', true),
  ('adapsys-colombia', 'a-ingresos-clientes', 'ADAPSYS COLOMBIA', 'ingreso', true),
  ('adapsys-peru', 'a-ingresos-clientes', 'ADAPSYS PERÚ', 'ingreso', true),
  ('agrosuper', 'a-ingresos-clientes', 'AGROSUPER', 'ingreso', true),
  ('aislapol', 'a-ingresos-clientes', 'AISLAPOL', 'ingreso', true),
  ('albemarle', 'a-ingresos-clientes', 'ALBEMARLE', 'ingreso', true),
  ('almagro', 'a-ingresos-clientes', 'ALMAGRO', 'ingreso', true),
  ('aln-programa-liderazgo', 'a-ingresos-clientes', 'ALN PROGRAMA LIDERAZGO', 'ingreso', true),
  ('alto-las-condes', 'a-ingresos-clientes', 'ALTO LAS CONDES', 'ingreso', true),
  ('amsa', 'a-ingresos-clientes', 'AMSA', 'ingreso', true),
  ('anasac', 'a-ingresos-clientes', 'ANASAC', 'ingreso', true),
  ('andritz', 'a-ingresos-clientes', 'ANDRITZ', 'ingreso', true),
  ('angloamerican', 'a-ingresos-clientes', 'ANGLOAMERICAN', 'ingreso', true),
  ('aon-corporation', 'a-ingresos-clientes', 'AON CORPORATION', 'ingreso', true),
  ('arcoprime', 'a-ingresos-clientes', 'ARCOPRIME', 'ingreso', true),
  ('asociacion-de-empresas-familiares', 'a-ingresos-clientes', 'ASOCIACIÓN DE EMPRESAS FAMILIARES', 'ingreso', true),
  ('astrazeneca', 'a-ingresos-clientes', 'ASTRAZENECA', 'ingreso', true),
  ('banchile', 'a-ingresos-clientes', 'BANCHILE', 'ingreso', true),
  ('banco-bci', 'a-ingresos-clientes', 'BANCO BCI', 'ingreso', true),
  ('banco-central', 'a-ingresos-clientes', 'BANCO CENTRAL', 'ingreso', true),
  ('banco-de-chile', 'a-ingresos-clientes', 'BANCO DE CHILE', 'ingreso', true),
  ('banco-estado-beco', 'a-ingresos-clientes', 'BANCO ESTADO BECO', 'ingreso', true),
  ('banco-itau', 'a-ingresos-clientes', 'BANCO ITAÚ', 'ingreso', true),
  ('banco-santander', 'a-ingresos-clientes', 'BANCO SANTANDER', 'ingreso', true),
  ('bbk', 'a-ingresos-clientes', 'BBK', 'ingreso', true),
  ('bbosch', 'a-ingresos-clientes', 'BBOSCH', 'ingreso', true),
  ('bechtel', 'a-ingresos-clientes', 'BECHTEL', 'ingreso', true),
  ('besalco', 'a-ingresos-clientes', 'BESALCO', 'ingreso', true),
  ('betterfly', 'a-ingresos-clientes', 'BETTERFLY', 'ingreso', true),
  ('bhp-billiton', 'a-ingresos-clientes', 'BHP BILLITON', 'ingreso', true),
  ('bice-corp', 'a-ingresos-clientes', 'BICE CORP', 'ingreso', true),
  ('bice-vida', 'a-ingresos-clientes', 'BICE VIDA', 'ingreso', true),
  ('biodiversa', 'a-ingresos-clientes', 'BIODIVERSA', 'ingreso', true),
  ('blumar', 'a-ingresos-clientes', 'BLUMAR', 'ingreso', true),
  ('burn-to-give', 'a-ingresos-clientes', 'BURN TO GIVE', 'ingreso', true),
  ('c-l-fruit', 'a-ingresos-clientes', 'C&L Fruit', 'ingreso', true),
  ('caja-los-andes', 'a-ingresos-clientes', 'CAJA LOS ANDES', 'ingreso', true),
  ('camara-de-comercio', 'a-ingresos-clientes', 'CÁMARA DE COMERCIO', 'ingreso', true),
  ('cap', 'a-ingresos-clientes', 'CAP', 'ingreso', true),
  ('cardif', 'a-ingresos-clientes', 'CARDIF', 'ingreso', true),
  ('carey', 'a-ingresos-clientes', 'CAREY', 'ingreso', true),
  ('cargill', 'a-ingresos-clientes', 'CARGILL', 'ingreso', true),
  ('caserones-lundin-mining', 'a-ingresos-clientes', 'CASERONES LUNDIN MINING', 'ingreso', true),
  ('cchc', 'a-ingresos-clientes', 'CCHC', 'ingreso', true),
  ('charlas-magistrales', 'a-ingresos-clientes', 'CHARLAS MAGISTRALES', 'ingreso', true),
  ('chilexpress', 'a-ingresos-clientes', 'CHILEXPRESS', 'ingreso', true),
  ('cla-consulting', 'a-ingresos-clientes', 'CLA CONSULTING', 'ingreso', true),
  ('cla-consultores', 'a-ingresos-clientes', 'CLA CONSULTORES', 'ingreso', true),
  ('cla-consultoria', 'a-ingresos-clientes', 'CLA CONSULTORÍA', 'ingreso', true),
  ('clinica-opia', 'a-ingresos-clientes', 'CLÍNICA OPIA', 'ingreso', true),
  ('club-mujeres-empresarias', 'a-ingresos-clientes', 'CLUB MUJERES EMPRESARIAS', 'ingreso', true),
  ('clue', 'a-ingresos-clientes', 'CLUE', 'ingreso', true),
  ('cmpc', 'a-ingresos-clientes', 'CMPC', 'ingreso', true),
  ('cmpc-softys', 'a-ingresos-clientes', 'CMPC SOFTYS', 'ingreso', true),
  ('coasin', 'a-ingresos-clientes', 'COASIN', 'ingreso', true),
  ('coca-cola-andina', 'a-ingresos-clientes', 'COCA COLA ANDINA', 'ingreso', true),
  ('codelco', 'a-ingresos-clientes', 'CODELCO', 'ingreso', true),
  ('colbun', 'a-ingresos-clientes', 'COLBUN', 'ingreso', true),
  ('colegio-alianza-francesa', 'a-ingresos-clientes', 'COLEGIO ALIANZA FRANCESA', 'ingreso', true),
  ('colegio-saint-joseph-school', 'a-ingresos-clientes', 'COLEGIO SAINT JOSEPH SCHOOL', 'ingreso', true),
  ('colmena', 'a-ingresos-clientes', 'COLMENA', 'ingreso', true),
  ('compass', 'a-ingresos-clientes', 'COMPASS', 'ingreso', true),
  ('consalud', 'a-ingresos-clientes', 'CONSALUD', 'ingreso', true),
  ('copec', 'a-ingresos-clientes', 'COPEC', 'ingreso', true),
  ('dfsi', 'a-ingresos-clientes', 'DFSI', 'ingreso', true),
  ('division-andina', 'a-ingresos-clientes', 'DIVISIÓN ANDINA', 'ingreso', true),
  ('division-salvador', 'a-ingresos-clientes', 'DIVISIÓN SALVADOR', 'ingreso', true),
  ('duoc-uc', 'a-ingresos-clientes', 'DUOC UC', 'ingreso', true),
  ('echeverria-izquierdo', 'a-ingresos-clientes', 'ECHEVERRÍA IZQUIERDO', 'ingreso', true),
  ('ecometales', 'a-ingresos-clientes', 'ECOMETALES', 'ingreso', true),
  ('edf', 'a-ingresos-clientes', 'EDF', 'ingreso', true),
  ('egt', 'a-ingresos-clientes', 'EGT', 'ingreso', true),
  ('el-mercurio', 'a-ingresos-clientes', 'EL MERCURIO', 'ingreso', true),
  ('emin', 'a-ingresos-clientes', 'EMIN', 'ingreso', true),
  ('empresas-demaria', 'a-ingresos-clientes', 'EMPRESAS DEMARIA', 'ingreso', true),
  ('empresas-salcobrand', 'a-ingresos-clientes', 'EMPRESAS SALCOBRAND', 'ingreso', true),
  ('empresas-sb', 'a-ingresos-clientes', 'EMPRESAS SB', 'ingreso', true),
  ('empresas-socovesa', 'a-ingresos-clientes', 'EMPRESAS SOCOVESA', 'ingreso', true),
  ('enap', 'a-ingresos-clientes', 'ENAP', 'ingreso', true),
  ('energia-rio-claro', 'a-ingresos-clientes', 'ENERGÍA RÍO CLARO', 'ingreso', true),
  ('entel', 'a-ingresos-clientes', 'ENTEL', 'ingreso', true),
  ('enthalpy', 'a-ingresos-clientes', 'ENTHALPY', 'ingreso', true),
  ('essbio', 'a-ingresos-clientes', 'ESSBIO', 'ingreso', true),
  ('essilorluxottica', 'a-ingresos-clientes', 'ESSILORLUXOTTICA', 'ingreso', true),
  ('essity', 'a-ingresos-clientes', 'ESSITY', 'ingreso', true),
  ('esval', 'a-ingresos-clientes', 'ESVAL', 'ingreso', true),
  ('evol', 'a-ingresos-clientes', 'EVOL', 'ingreso', true),
  ('falabella', 'a-ingresos-clientes', 'FALABELLA', 'ingreso', true),
  ('fedefruta', 'a-ingresos-clientes', 'FEDEFRUTA', 'ingreso', true),
  ('ferradanehme', 'a-ingresos-clientes', 'FERRADANEHME', 'ingreso', true),
  ('finix', 'a-ingresos-clientes', 'FINIX', 'ingreso', true),
  ('fundacion-belen-educa', 'a-ingresos-clientes', 'FUNDACIÓN BELEN EDUCA', 'ingreso', true),
  ('fundacion-gantz', 'a-ingresos-clientes', 'FUNDACION GANTZ', 'ingreso', true),
  ('fundacion-nuestros-hijos', 'a-ingresos-clientes', 'FUNDACIÓN NUESTROS HIJOS', 'ingreso', true),
  ('furoiani', 'a-ingresos-clientes', 'FUROIANI', 'ingreso', true),
  ('goldfield', 'a-ingresos-clientes', 'GOLDFIELD', 'ingreso', true),
  ('grupo-rcd', 'a-ingresos-clientes', 'GRUPO RCD', 'ingreso', true),
  ('grupo-security', 'a-ingresos-clientes', 'GRUPO SECURITY', 'ingreso', true),
  ('grylan', 'a-ingresos-clientes', 'GRYLAN', 'ingreso', true),
  ('gtd', 'a-ingresos-clientes', 'GTD', 'ingreso', true),
  ('hotel-talbot', 'a-ingresos-clientes', 'HOTEL TALBOT', 'ingreso', true),
  ('iconstruye', 'a-ingresos-clientes', 'ICONSTRUYE', 'ingreso', true),
  ('ieside', 'a-ingresos-clientes', 'IESIDE', 'ingreso', true),
  ('iff', 'a-ingresos-clientes', 'IFF', 'ingreso', true),
  ('inchcape', 'a-ingresos-clientes', 'INCHCAPE', 'ingreso', true),
  ('irade', 'a-ingresos-clientes', 'IRADE', 'ingreso', true),
  ('knauf', 'a-ingresos-clientes', 'KNAUF', 'ingreso', true),
  ('komatsu', 'a-ingresos-clientes', 'KOMATSU', 'ingreso', true),
  ('kpmg-chile', 'a-ingresos-clientes', 'KPMG CHILE', 'ingreso', true),
  ('kyndryl', 'a-ingresos-clientes', 'KYNDRYL', 'ingreso', true),
  ('laad', 'a-ingresos-clientes', 'LAAD', 'ingreso', true),
  ('laboratorio-janssen', 'a-ingresos-clientes', 'LABORATORIO JANSSEN', 'ingreso', true),
  ('laboratorios-saval-s-a', 'a-ingresos-clientes', 'LABORATORIOS SAVAL S.A.', 'ingreso', true),
  ('larrain-vial', 'a-ingresos-clientes', 'LARRAÍN VIAL', 'ingreso', true),
  ('mall-plaza', 'a-ingresos-clientes', 'MALL PLAZA', 'ingreso', true),
  ('mas-analytics', 'a-ingresos-clientes', 'MAS ANALYTICS', 'ingreso', true),
  ('mas-errazuriz', 'a-ingresos-clientes', 'MAS ERRAZURIZ', 'ingreso', true),
  ('masisa', 'a-ingresos-clientes', 'MASISA', 'ingreso', true),
  ('metagroup', 'a-ingresos-clientes', 'METAGROUP', 'ingreso', true),
  ('metlife', 'a-ingresos-clientes', 'METLIFE', 'ingreso', true),
  ('metso-chile', 'a-ingresos-clientes', 'METSO CHILE', 'ingreso', true),
  ('minera-florida', 'a-ingresos-clientes', 'MINERA FLORIDA', 'ingreso', true),
  ('minsait-indra', 'a-ingresos-clientes', 'MINSAIT INDRA', 'ingreso', true),
  ('mitsui-auto-finance', 'a-ingresos-clientes', 'MITSUI AUTO FINANCE', 'ingreso', true),
  ('molymet', 'a-ingresos-clientes', 'MOLYMET', 'ingreso', true),
  ('monarch', 'a-ingresos-clientes', 'MONARCH', 'ingreso', true),
  ('mts', 'a-ingresos-clientes', 'MTS', 'ingreso', true),
  ('mutual-de-seguridad', 'a-ingresos-clientes', 'MUTUAL DE SEGURIDAD', 'ingreso', true),
  ('nestle', 'a-ingresos-clientes', 'NESTLE', 'ingreso', true),
  ('nttdata', 'a-ingresos-clientes', 'NTTDATA', 'ingreso', true),
  ('ogilvy', 'a-ingresos-clientes', 'Ogilvy', 'ingreso', true),
  ('ohl', 'a-ingresos-clientes', 'OHL', 'ingreso', true),
  ('old-navy', 'a-ingresos-clientes', 'OLD NAVY', 'ingreso', true),
  ('opia-marketing', 'a-ingresos-clientes', 'OPIA MARKETING', 'ingreso', true),
  ('oracle', 'a-ingresos-clientes', 'ORACLE', 'ingreso', true),
  ('oxiquim', 'a-ingresos-clientes', 'OXIQUIM', 'ingreso', true),
  ('papelera-lo-izquierdo', 'a-ingresos-clientes', 'PAPELERA LO IZQUIERDO', 'ingreso', true),
  ('parque-arauco', 'a-ingresos-clientes', 'PARQUE ARAUCO', 'ingreso', true),
  ('pflp', 'a-ingresos-clientes', 'PFLP', 'ingreso', true),
  ('pisquera-de-chile', 'a-ingresos-clientes', 'PISQUERA DE CHILE', 'ingreso', true),
  ('plaza-maule', 'a-ingresos-clientes', 'PLAZA MAULE', 'ingreso', true),
  ('porsche', 'a-ingresos-clientes', 'PORSCHE', 'ingreso', true),
  ('pragmaxion', 'a-ingresos-clientes', 'PRAGMAXION', 'ingreso', true),
  ('prestigio', 'a-ingresos-clientes', 'PRESTIGIO', 'ingreso', true),
  ('promigas', 'a-ingresos-clientes', 'PROMIGAS', 'ingreso', true),
  ('pronto-espacio', 'a-ingresos-clientes', 'PRONTO ESPACIO', 'ingreso', true),
  ('prosegur', 'a-ingresos-clientes', 'PROSEGUR', 'ingreso', true),
  ('pucobre', 'a-ingresos-clientes', 'PUCOBRE', 'ingreso', true),
  ('quimica-latinoamericana', 'a-ingresos-clientes', 'QUÍMICA LATINOAMERICANA', 'ingreso', true),
  ('red-igualdad', 'a-ingresos-clientes', 'RED IGUALDAD', 'ingreso', true),
  ('ride', 'a-ingresos-clientes', 'RIDE', 'ingreso', true),
  ('roche', 'a-ingresos-clientes', 'ROCHE', 'ingreso', true),
  ('salfa', 'a-ingresos-clientes', 'SALFA', 'ingreso', true),
  ('scotiabank', 'a-ingresos-clientes', 'SCOTIABANK', 'ingreso', true),
  ('scretting', 'a-ingresos-clientes', 'SCRETTING', 'ingreso', true),
  ('servicio-civil', 'a-ingresos-clientes', 'SERVICIO CIVIL', 'ingreso', true),
  ('simon-de-cirene', 'a-ingresos-clientes', 'SIMON DE CIRENE', 'ingreso', true),
  ('sinacofi', 'a-ingresos-clientes', 'SINACOFI', 'ingreso', true),
  ('sk', 'a-ingresos-clientes', 'SK', 'ingreso', true),
  ('sky-airlines', 'a-ingresos-clientes', 'SKY AIRLINES', 'ingreso', true),
  ('softys', 'a-ingresos-clientes', 'SOFTYS', 'ingreso', true),
  ('southbridge', 'a-ingresos-clientes', 'SOUTHBRIDGE', 'ingreso', true),
  ('starken', 'a-ingresos-clientes', 'STARKEN', 'ingreso', true),
  ('statkraft', 'a-ingresos-clientes', 'STATKRAFT', 'ingreso', true),
  ('sura', 'a-ingresos-clientes', 'SURA', 'ingreso', true),
  ('systep', 'a-ingresos-clientes', 'SYSTEP', 'ingreso', true),
  ('tanner', 'a-ingresos-clientes', 'TANNER', 'ingreso', true),
  ('teck', 'a-ingresos-clientes', 'TECK', 'ingreso', true),
  ('testcloud', 'a-ingresos-clientes', 'TESTCLOUD', 'ingreso', true),
  ('tgr', 'a-ingresos-clientes', 'TGR', 'ingreso', true),
  ('the-coca-cola-company', 'a-ingresos-clientes', 'THE COCA-COLA COMPANY', 'ingreso', true),
  ('tigre-ads', 'a-ingresos-clientes', 'TIGRE/ADS', 'ingreso', true),
  ('timining', 'a-ingresos-clientes', 'TIMINING', 'ingreso', true),
  ('toctoc', 'a-ingresos-clientes', 'TOCTOC', 'ingreso', true),
  ('tottus', 'a-ingresos-clientes', 'TOTTUS', 'ingreso', true),
  ('transelec', 'a-ingresos-clientes', 'TRANSELEC', 'ingreso', true),
  ('trendy', 'a-ingresos-clientes', 'TRENDY', 'ingreso', true),
  ('tres-montes', 'a-ingresos-clientes', 'TRES MONTES', 'ingreso', true),
  ('triciclos', 'a-ingresos-clientes', 'TRICICLOS', 'ingreso', true),
  ('uai', 'a-ingresos-clientes', 'UAI', 'ingreso', true),
  ('universidad-adolfo-ibanez', 'a-ingresos-clientes', 'UNIVERSIDAD ADOLFO IBAÑEZ', 'ingreso', true),
  ('universidad-de-atacama', 'a-ingresos-clientes', 'UNIVERSIDAD DE ATACAMA', 'ingreso', true),
  ('universidad-san-sebastian', 'a-ingresos-clientes', 'UNIVERSIDAD SAN SEBASTIAN', 'ingreso', true),
  ('uno-salud', 'a-ingresos-clientes', 'UNO SALUD', 'ingreso', true),
  ('vantaz', 'a-ingresos-clientes', 'VANTAZ', 'ingreso', true),
  ('vida-camara', 'a-ingresos-clientes', 'VIDA CAMARA', 'ingreso', true),
  ('walmart', 'a-ingresos-clientes', 'WALMART', 'ingreso', true),
  ('wec', 'a-ingresos-clientes', 'WEC', 'ingreso', true),
  ('zurich', 'a-ingresos-clientes', 'ZURICH', 'ingreso', true),
  ('otros-ingresos', 'b-otros-ingresos', 'Otros ingresos', 'ingreso', true),
  ('prestamos-bancarios', 'b-otros-ingresos', 'Prestamos bancarios', 'ingreso', true),
  ('prestamos-relacionadas', 'b-otros-ingresos', 'Prestamos relacionadas', 'ingreso', true),
  ('utilidades-colombia', 'b-otros-ingresos', 'Utilidades Colombia', 'ingreso', true),
  ('utilidades-peru', 'b-otros-ingresos', 'Utilidades Perú', 'ingreso', true),
  ('conferencias', '1-costo-de-venta', 'Conferencias', 'operativo', true),
  ('costos-directos-consultoria', '1-costo-de-venta', 'Costos directos consultoría', 'operativo', true),
  ('costos-directos-consultoria-equipa', '1-costo-de-venta', 'Costos directos consultoría - Equipamiento tecnológico Salvador', 'operativo', true),
  ('costos-directos-consultoria-examen', '1-costo-de-venta', 'Costos directos consultoría - Exámenes y certificaciones Salvador', 'operativo', true),
  ('costos-directos-consultoria-logist', '1-costo-de-venta', 'Costos directos consultoría - Logística Salvador', 'operativo', true),
  ('costos-directos-consultoria-materi', '1-costo-de-venta', 'Costos directos consultoría - Materiales Salvador', 'operativo', true),
  ('distribucion-de-margen', '1-costo-de-venta', 'Distribución de margen', 'operativo', true),
  ('generacion-de-contenido', '1-costo-de-venta', 'Generación de contenido', 'operativo', true),
  ('horas', '1-costo-de-venta', 'Horas', 'operativo', true),
  ('ingreso-minimo-asegurado', '1-costo-de-venta', 'Ingreso mínimo asegurado', 'operativo', true),
  ('jefaturas', '1-costo-de-venta', 'Jefaturas', 'operativo', true),
  ('actividades-aprendizaje-organizaci', '1-desarrollo-organizaciona', 'Actividades aprendizaje organizacional', 'inversion', true),
  ('asesoria-proy-desarrollo-interno', '1-desarrollo-organizaciona', 'AsesorÍa Proy. Desarrollo Interno', 'inversion', true),
  ('asesoria-proyectos-probono', '1-desarrollo-organizaciona', 'Asesoría proyectos Probono', 'inversion', true),
  ('capacitacion-consultores', '1-desarrollo-organizaciona', 'Capacitación Consultores', 'operativo', true),
  ('coalicion-de-cambio', '1-desarrollo-organizaciona', 'Coalición de cambio', 'inversion', true),
  ('consultoria-y-gestion-de-proyectos', '1-desarrollo-organizaciona', 'Consultoría y gestión de proyectos', 'inversion', true),
  ('direccion-ejecutiva', '1-desarrollo-organizaciona', 'Dirección Ejecutiva', 'inversion', true),
  ('proyecto-formacion', '1-desarrollo-organizaciona', 'Proyecto formación', 'inversion', true),
  ('reparto-de-utilidades-anuales', '1-desarrollo-organizaciona', 'Reparto de utilidades anuales', 'inversion', true),
  ('arriendo-oficina', '2-gastos-administracion', 'Arriendo oficina', 'operativo', true),
  ('asesoria-contable', '2-gastos-administracion', 'Asesoría contable', 'operativo', true),
  ('beneficios-personas', '2-gastos-administracion', 'Beneficios personas', 'operativo', true),
  ('caja-chica', '2-gastos-administracion', 'Caja chica', 'operativo', true),
  ('certificaciones', '2-gastos-administracion', 'Certificaciones', 'inversion', true),
  ('contribuciones', '2-gastos-administracion', 'Contribuciones', 'operativo', true),
  ('equipamiento-oficina', '2-gastos-administracion', 'Equipamiento oficina', 'inversion', true),
  ('gastos-comunes', '2-gastos-administracion', 'Gastos comunes', 'operativo', true),
  ('gastos-de-representacion', '2-gastos-administracion', 'Gastos de representación', 'operativo', true),
  ('gastos-legales', '2-gastos-administracion', 'Gastos legales', 'operativo', true),
  ('insumos-oficina', '2-gastos-administracion', 'Insumos oficina', 'operativo', true),
  ('jornadas-y-eventos-organizacion', '2-gastos-administracion', 'Jornadas y eventos organizacion', 'operativo', true),
  ('offsite-internacional', '2-gastos-administracion', 'Offsite internacional', 'operativo', true),
  ('mant-y-reparacion-oficina', '2-gastos-administracion', 'Mant. y Reparación oficina', 'operativo', true),
  ('patente-comercial', '2-gastos-administracion', 'Patente comercial', 'operativo', true),
  ('telefonia-e-internet', '2-gastos-administracion', 'Telefonía e internet', 'operativo', true),
  ('agencia-comunicaciones', '2-0-comercial-y-marketing', 'Agencia comunicaciones', 'inversion', true),
  ('alianzas-estudios-y-relacionamient', '2-0-comercial-y-marketing', 'Alianzas, estudios y relacionamiento', 'inversion', true),
  ('asistencia-a-eventos', '2-0-comercial-y-marketing', 'Asistencia a eventos', 'operativo', true),
  ('estudios-publicos', '2-0-comercial-y-marketing', 'Estudios públicos', 'inversion', true),
  ('eventos-propios', '2-0-comercial-y-marketing', 'Eventos propios', 'inversion', true),
  ('gastos-de-marketing', '2-0-comercial-y-marketing', 'Gastos de marketing', 'operativo', true),
  ('marketing-digital', '2-0-comercial-y-marketing', 'Marketing digital', 'inversion', true),
  ('medios-digitales', '2-0-comercial-y-marketing', 'Medios digitales', 'operativo', true),
  ('pagina-web', '2-0-comercial-y-marketing', 'Página web', 'inversion', true),
  ('branding-y-merchandising', '2-1-posicionamiento-nueva', 'Branding y merchandising', 'inversion', true),
  ('difusion-nueva-marca', '2-1-posicionamiento-nueva', 'Difusión nueva marca', 'inversion', true),
  ('nueva-marca-organizacional', '2-1-posicionamiento-nueva', 'Nueva marca organizacional', 'inversion', true),
  ('2-1-posicionamiento-nueva-pagina-web', '2-1-posicionamiento-nueva', 'Pagina web', 'inversion', true),
  ('registro-legales-nueva-marca', '2-1-posicionamiento-nueva', 'Registro legales nueva marca', 'inversion', true),
  ('garantias', '2-2-compra-activos', 'Garantías', 'inversion', true),
  ('infraestructura', '2-2-compra-activos', 'Infraestructura', 'inversion', true),
  ('legales-y-puesta-en-marcha', '2-2-compra-activos', 'Legales y puesta en marcha', 'inversion', true),
  ('muebles-y-enseres', '2-2-compra-activos', 'Muebles y enseres', 'inversion', true),
  ('propiedades-oficina', '2-2-compra-activos', 'Propiedades (Oficina)', 'inversion', true),
  ('gastos-sistemas-digitales', '2-3-gastos-sistemas-digita', 'Gastos sistemas digitales', 'operativo', true),
  ('sistemas-analitica-avanzada-ia-y-r', '2-3-gastos-sistemas-digita', 'Sistemas Analítica avanzada, IA y Relac.', 'operativo', true),
  ('sistemas-diseno', '2-3-gastos-sistemas-digita', 'Sistemas Diseño', 'inversion', true),
  ('sistemas-operaciones', '2-3-gastos-sistemas-digita', 'Sistemas Operaciones', 'operativo', true),
  ('sistemas-operaciones-y-finanzas', '2-3-gastos-sistemas-digita', 'Sistemas Operaciones y Finanzas', 'operativo', true),
  ('equipos-computacionales', '2-4-equipos-computacionale', 'Equipos Computacionales', 'inversion', true),
  ('mantenimiento-equipos', '2-4-equipos-computacionale', 'Mantenimiento Equipos', 'operativo', true),
  ('capacitacion-del-personal', '3-recursos-humanos', 'Capacitación del personal', 'inversion', true),
  ('finiquitos', '3-recursos-humanos', 'Finiquitos', 'operativo', true),
  ('imposiciones', '3-recursos-humanos', 'Imposiciones', 'operativo', true),
  ('jornadas-y-eventos-equipo-interno', '3-recursos-humanos', 'Jornadas y eventos equipo interno', 'operativo', true),
  ('servicios-externos-rr-hh', '3-recursos-humanos', 'Servicios externos RR.HH', 'operativo', true),
  ('sueldos', '3-recursos-humanos', 'Sueldos', 'operativo', true),
  ('impuesto-a-la-renta', '4-impuestos', 'Impuesto a la renta', 'operativo', true),
  ('iva-compras', '4-impuestos', 'IVA compras', 'operativo', true),
  ('iva-mensual', '4-impuestos', 'IVA mensual', 'operativo', true),
  ('retencion-bhe', '4-impuestos', 'Retención BHE', 'operativo', true),
  ('comisiones-bancarias', '5-bancos', 'Comisiones bancarias', 'operativo', true),
  ('tarjeta-de-credito', '5-bancos', 'Tarjeta de credito', 'operativo', true),
  ('traspaso-entre-empresas', '5-bancos', 'Traspaso entre empresas', 'operativo', true),
  ('prestamos-bancarios-pago', '6-prestamos-bancarios', 'Prestamos bancarios (pago)', 'operativo', true),
  ('depositos-a-plazo', '7-inversiones', 'Depositos a plazo', 'operativo', true),
  ('firmex', '7-inversiones', 'Firmex', 'operativo', true),
  ('fondos-mutuos', '7-inversiones', 'Fondos mutuos', 'operativo', true),
  ('invexor', '7-inversiones', 'Invexor', 'operativo', true),
  ('poliglota', '7-inversiones', 'Poliglota', 'operativo', true),
  ('adapsys-miami', '8-relacionados-y-socios', 'Adapsys Miami', 'operativo', true),
  ('cuenta-corriente-peru-chile', '8-relacionados-y-socios', 'Cuenta corriente Perú-Chile', 'operativo', true),
  ('participacion-comite', '8-relacionados-y-socios', 'Participación Comité', 'operativo', true),
  ('prestamos-socios', '8-relacionados-y-socios', 'Préstamos socios', 'operativo', true),
  ('retiros-socios', '8-relacionados-y-socios', 'Retiros socios', 'operativo', true);

-- Parámetros con vigencia por año (§9) — verificar la tasa BHE vigente con el SII
-- antes de dar por buena la de 2026 (Ley 21.133, escala hasta 2028).
insert into parametros (clave, valor, vigencia_desde) values
  ('tasa_iva', 0.19, '2000-01-01'),
  ('tasa_bhe', 0.1525, '2026-01-01'),
  ('tc_presupuesto', 970, '2026-01-01');
