// Catálogo real de Adapsys — 16 categorías, 284 subcategorías (CLAUDE.md §5).
// Generado una vez desde tesoreria.jsx con scripts/gen_catalogo.py.
// ESTA es la fuente de verdad: scripts/gen_seed.py lee este archivo para
// producir supabase/seed.sql. Editar acá, nunca el SQL.

import type { Categoria, Cuenta, Empresa, Naturaleza, Subcategoria } from "@/lib/tipos";

/** Etiqueta larga de cada grupo, para la UI. */
export const GRUPOS = [
  { id: "Adapsys" as const, nombre: "Adapsys" },
  { id: "Relacionadas" as const, nombre: "Empresas relacionadas" },
];

export const EMPRESAS: Empresa[] = [
  { id: "adap", nombre: "CLA ADAPTACIÓN", corto: "ADAP", grupo: "Adapsys" },
  { id: "cons", nombre: "CLA CONSULTORES", corto: "CONS", grupo: "Adapsys" },
  { id: "clting", nombre: "CLA CONSULTING", corto: "CLTG", grupo: "Adapsys" },
  { id: "ctria", nombre: "CLA CONSULTORIA", corto: "CTRIA", grupo: "Adapsys" },
  { id: "sm", nombre: "SANTA MARÍA", corto: "SM", grupo: "Relacionadas" },
];

export const IDS_ADAPSYS = EMPRESAS.filter((e) => e.grupo === "Adapsys").map((e) => e.id);

/** Presets del filtro global de empresas. */
export const PRESETS_EMPRESA = [
  { id: "ads", nombre: "Adapsys", ids: IDS_ADAPSYS },
  { id: "todas", nombre: "Todas", ids: EMPRESAS.map((e) => e.id) },
  { id: "rel", nombre: "Relacionadas", ids: ["sm"] },
];

export const CUENTAS: Cuenta[] = [
  { id: "a1", empresa_id: "adap", nombre: "CLA ADAPTACIÓN PESOS", moneda: "CLP", tipo: "banco", saldo_inicial: 199673281, principal: true },
  { id: "a2", empresa_id: "adap", nombre: "CLA ADAPTACIÓN DÓLAR", moneda: "USD", tipo: "banco", saldo_inicial: 53, principal: false },
  { id: "b1", empresa_id: "cons", nombre: "CLA CONSULTORES PESOS", moneda: "CLP", tipo: "banco", saldo_inicial: 4866278, principal: true },
  { id: "b2", empresa_id: "cons", nombre: "CLA CONSULTORES DÓLAR", moneda: "USD", tipo: "banco", saldo_inicial: 4746, principal: false },
  { id: "c1", empresa_id: "clting", nombre: "CLA CONSULTING PESOS", moneda: "CLP", tipo: "banco", saldo_inicial: 185642497, principal: true },
  { id: "c2", empresa_id: "clting", nombre: "CLA CONSULTING DÓLAR", moneda: "USD", tipo: "banco", saldo_inicial: 21, principal: false },
  { id: "d1", empresa_id: "ctria", nombre: "CLA CONSULTORIA PESOS", moneda: "CLP", tipo: "banco", saldo_inicial: 2731975, principal: true },
  { id: "e1", empresa_id: "sm", nombre: "SANTA MARÍA PESOS", moneda: "CLP", tipo: "banco", saldo_inicial: -132518, principal: true },
  { id: "e2", empresa_id: "sm", nombre: "SANTA MARÍA DÓLAR", moneda: "USD", tipo: "banco", saldo_inicial: 1000, principal: false },
  { id: "x1", empresa_id: "adap", nombre: "Facturas por cobrar CLP", moneda: "CLP", tipo: "cxc", saldo_inicial: 0, principal: false },
  { id: "x2", empresa_id: "adap", nombre: "Facturas por cobrar USD", moneda: "USD", tipo: "cxc", saldo_inicial: 16285, principal: false },
];

export const NATURALEZAS: { id: Naturaleza; nombre: string }[] = [
  { id: "ingreso", nombre: "Ingresos" },
  { id: "inversion", nombre: "Gastos de Inversión" },
  { id: "operativo", nombre: "Gastos Operativos" },
];

export const RESPONSABLES = [
  "", "I+D", "Analítica avanzada", "Finanzas", "Personas", "Comercial", "Gerencia",
];

export const CATEGORIAS: Categoria[] = [
  { id: "a-ingresos-clientes", nombre: "A INGRESOS CLIENTES", orden: 0, controlado: true },
  { id: "b-otros-ingresos", nombre: "B OTROS INGRESOS", orden: 1, controlado: true },
  { id: "1-costo-de-venta", nombre: "1 COSTO DE VENTA", orden: 2, controlado: true },
  { id: "1-desarrollo-organizaciona", nombre: "1 DESARROLLO ORGANIZACIONAL", orden: 3, controlado: true },
  { id: "2-gastos-administracion", nombre: "2 GASTOS ADMINISTRACIÓN", orden: 4, controlado: true },
  { id: "2-0-comercial-y-marketing", nombre: "2.0 COMERCIAL Y MARKETING", orden: 5, controlado: true },
  { id: "2-1-posicionamiento-nueva", nombre: "2.1 POSICIONAMIENTO NUEVA MARCA", orden: 6, controlado: true },
  { id: "2-2-compra-activos", nombre: "2.2 COMPRA ACTIVOS", orden: 7, controlado: true },
  { id: "2-3-gastos-sistemas-digita", nombre: "2.3 GASTOS SISTEMAS DIGITALES", orden: 8, controlado: true },
  { id: "2-4-equipos-computacionale", nombre: "2.4 EQUIPOS COMPUTACIONALES", orden: 9, controlado: true },
  { id: "3-recursos-humanos", nombre: "3 RECURSOS HUMANOS", orden: 10, controlado: true },
  { id: "4-impuestos", nombre: "4 IMPUESTOS", orden: 11, controlado: true },
  { id: "5-bancos", nombre: "5 BANCOS", orden: 12, controlado: true },
  { id: "6-prestamos-bancarios", nombre: "6 PRESTAMOS BANCARIOS", orden: 13, controlado: false },
  { id: "7-inversiones", nombre: "7 INVERSIONES", orden: 14, controlado: false },
  { id: "8-relacionados-y-socios", nombre: "8 RELACIONADOS Y SOCIOS", orden: 15, controlado: false },
];

export const SUBCATEGORIAS: Subcategoria[] = [
  { id: "aasa", categoria_id: "a-ingresos-clientes", nombre: "AASA", naturaleza: "ingreso", activa: true },
  { id: "abastible", categoria_id: "a-ingresos-clientes", nombre: "ABASTIBLE", naturaleza: "ingreso", activa: true },
  { id: "acciona", categoria_id: "a-ingresos-clientes", nombre: "ACCIONA", naturaleza: "ingreso", activa: true },
  { id: "achs", categoria_id: "a-ingresos-clientes", nombre: "ACHS", naturaleza: "ingreso", activa: true },
  { id: "adapsys-australia", categoria_id: "a-ingresos-clientes", nombre: "ADAPSYS AUSTRALIA", naturaleza: "ingreso", activa: true },
  { id: "adapsys-colombia", categoria_id: "a-ingresos-clientes", nombre: "ADAPSYS COLOMBIA", naturaleza: "ingreso", activa: true },
  { id: "adapsys-peru", categoria_id: "a-ingresos-clientes", nombre: "ADAPSYS PERÚ", naturaleza: "ingreso", activa: true },
  { id: "agrosuper", categoria_id: "a-ingresos-clientes", nombre: "AGROSUPER", naturaleza: "ingreso", activa: true },
  { id: "aislapol", categoria_id: "a-ingresos-clientes", nombre: "AISLAPOL", naturaleza: "ingreso", activa: true },
  { id: "albemarle", categoria_id: "a-ingresos-clientes", nombre: "ALBEMARLE", naturaleza: "ingreso", activa: true },
  { id: "almagro", categoria_id: "a-ingresos-clientes", nombre: "ALMAGRO", naturaleza: "ingreso", activa: true },
  { id: "aln-programa-liderazgo", categoria_id: "a-ingresos-clientes", nombre: "ALN PROGRAMA LIDERAZGO", naturaleza: "ingreso", activa: true },
  { id: "alto-las-condes", categoria_id: "a-ingresos-clientes", nombre: "ALTO LAS CONDES", naturaleza: "ingreso", activa: true },
  { id: "amsa", categoria_id: "a-ingresos-clientes", nombre: "AMSA", naturaleza: "ingreso", activa: true },
  { id: "anasac", categoria_id: "a-ingresos-clientes", nombre: "ANASAC", naturaleza: "ingreso", activa: true },
  { id: "andritz", categoria_id: "a-ingresos-clientes", nombre: "ANDRITZ", naturaleza: "ingreso", activa: true },
  { id: "angloamerican", categoria_id: "a-ingresos-clientes", nombre: "ANGLOAMERICAN", naturaleza: "ingreso", activa: true },
  { id: "aon-corporation", categoria_id: "a-ingresos-clientes", nombre: "AON CORPORATION", naturaleza: "ingreso", activa: true },
  { id: "arcoprime", categoria_id: "a-ingresos-clientes", nombre: "ARCOPRIME", naturaleza: "ingreso", activa: true },
  { id: "asociacion-de-empresas-familiares", categoria_id: "a-ingresos-clientes", nombre: "ASOCIACIÓN DE EMPRESAS FAMILIARES", naturaleza: "ingreso", activa: true },
  { id: "astrazeneca", categoria_id: "a-ingresos-clientes", nombre: "ASTRAZENECA", naturaleza: "ingreso", activa: true },
  { id: "banchile", categoria_id: "a-ingresos-clientes", nombre: "BANCHILE", naturaleza: "ingreso", activa: true },
  { id: "banco-bci", categoria_id: "a-ingresos-clientes", nombre: "BANCO BCI", naturaleza: "ingreso", activa: true },
  { id: "banco-central", categoria_id: "a-ingresos-clientes", nombre: "BANCO CENTRAL", naturaleza: "ingreso", activa: true },
  { id: "banco-de-chile", categoria_id: "a-ingresos-clientes", nombre: "BANCO DE CHILE", naturaleza: "ingreso", activa: true },
  { id: "banco-estado-beco", categoria_id: "a-ingresos-clientes", nombre: "BANCO ESTADO BECO", naturaleza: "ingreso", activa: true },
  { id: "banco-itau", categoria_id: "a-ingresos-clientes", nombre: "BANCO ITAÚ", naturaleza: "ingreso", activa: true },
  { id: "banco-santander", categoria_id: "a-ingresos-clientes", nombre: "BANCO SANTANDER", naturaleza: "ingreso", activa: true },
  { id: "bbk", categoria_id: "a-ingresos-clientes", nombre: "BBK", naturaleza: "ingreso", activa: true },
  { id: "bbosch", categoria_id: "a-ingresos-clientes", nombre: "BBOSCH", naturaleza: "ingreso", activa: true },
  { id: "bechtel", categoria_id: "a-ingresos-clientes", nombre: "BECHTEL", naturaleza: "ingreso", activa: true },
  { id: "besalco", categoria_id: "a-ingresos-clientes", nombre: "BESALCO", naturaleza: "ingreso", activa: true },
  { id: "betterfly", categoria_id: "a-ingresos-clientes", nombre: "BETTERFLY", naturaleza: "ingreso", activa: true },
  { id: "bhp-billiton", categoria_id: "a-ingresos-clientes", nombre: "BHP BILLITON", naturaleza: "ingreso", activa: true },
  { id: "bice-corp", categoria_id: "a-ingresos-clientes", nombre: "BICE CORP", naturaleza: "ingreso", activa: true },
  { id: "bice-vida", categoria_id: "a-ingresos-clientes", nombre: "BICE VIDA", naturaleza: "ingreso", activa: true },
  { id: "biodiversa", categoria_id: "a-ingresos-clientes", nombre: "BIODIVERSA", naturaleza: "ingreso", activa: true },
  { id: "blumar", categoria_id: "a-ingresos-clientes", nombre: "BLUMAR", naturaleza: "ingreso", activa: true },
  { id: "burn-to-give", categoria_id: "a-ingresos-clientes", nombre: "BURN TO GIVE", naturaleza: "ingreso", activa: true },
  { id: "c-l-fruit", categoria_id: "a-ingresos-clientes", nombre: "C&L Fruit", naturaleza: "ingreso", activa: true },
  { id: "caja-los-andes", categoria_id: "a-ingresos-clientes", nombre: "CAJA LOS ANDES", naturaleza: "ingreso", activa: true },
  { id: "camara-de-comercio", categoria_id: "a-ingresos-clientes", nombre: "CÁMARA DE COMERCIO", naturaleza: "ingreso", activa: true },
  { id: "cap", categoria_id: "a-ingresos-clientes", nombre: "CAP", naturaleza: "ingreso", activa: true },
  { id: "cardif", categoria_id: "a-ingresos-clientes", nombre: "CARDIF", naturaleza: "ingreso", activa: true },
  { id: "carey", categoria_id: "a-ingresos-clientes", nombre: "CAREY", naturaleza: "ingreso", activa: true },
  { id: "cargill", categoria_id: "a-ingresos-clientes", nombre: "CARGILL", naturaleza: "ingreso", activa: true },
  { id: "caserones-lundin-mining", categoria_id: "a-ingresos-clientes", nombre: "CASERONES LUNDIN MINING", naturaleza: "ingreso", activa: true },
  { id: "cchc", categoria_id: "a-ingresos-clientes", nombre: "CCHC", naturaleza: "ingreso", activa: true },
  { id: "charlas-magistrales", categoria_id: "a-ingresos-clientes", nombre: "CHARLAS MAGISTRALES", naturaleza: "ingreso", activa: true },
  { id: "chilexpress", categoria_id: "a-ingresos-clientes", nombre: "CHILEXPRESS", naturaleza: "ingreso", activa: true },
  { id: "cla-consulting", categoria_id: "a-ingresos-clientes", nombre: "CLA CONSULTING", naturaleza: "ingreso", activa: true },
  { id: "cla-consultores", categoria_id: "a-ingresos-clientes", nombre: "CLA CONSULTORES", naturaleza: "ingreso", activa: true },
  { id: "cla-consultoria", categoria_id: "a-ingresos-clientes", nombre: "CLA CONSULTORÍA", naturaleza: "ingreso", activa: true },
  { id: "clinica-opia", categoria_id: "a-ingresos-clientes", nombre: "CLÍNICA OPIA", naturaleza: "ingreso", activa: true },
  { id: "club-mujeres-empresarias", categoria_id: "a-ingresos-clientes", nombre: "CLUB MUJERES EMPRESARIAS", naturaleza: "ingreso", activa: true },
  { id: "clue", categoria_id: "a-ingresos-clientes", nombre: "CLUE", naturaleza: "ingreso", activa: true },
  { id: "cmpc", categoria_id: "a-ingresos-clientes", nombre: "CMPC", naturaleza: "ingreso", activa: true },
  { id: "cmpc-softys", categoria_id: "a-ingresos-clientes", nombre: "CMPC SOFTYS", naturaleza: "ingreso", activa: true },
  { id: "coasin", categoria_id: "a-ingresos-clientes", nombre: "COASIN", naturaleza: "ingreso", activa: true },
  { id: "coca-cola-andina", categoria_id: "a-ingresos-clientes", nombre: "COCA COLA ANDINA", naturaleza: "ingreso", activa: true },
  { id: "codelco", categoria_id: "a-ingresos-clientes", nombre: "CODELCO", naturaleza: "ingreso", activa: true },
  { id: "colbun", categoria_id: "a-ingresos-clientes", nombre: "COLBUN", naturaleza: "ingreso", activa: true },
  { id: "colegio-alianza-francesa", categoria_id: "a-ingresos-clientes", nombre: "COLEGIO ALIANZA FRANCESA", naturaleza: "ingreso", activa: true },
  { id: "colegio-saint-joseph-school", categoria_id: "a-ingresos-clientes", nombre: "COLEGIO SAINT JOSEPH SCHOOL", naturaleza: "ingreso", activa: true },
  { id: "colmena", categoria_id: "a-ingresos-clientes", nombre: "COLMENA", naturaleza: "ingreso", activa: true },
  { id: "compass", categoria_id: "a-ingresos-clientes", nombre: "COMPASS", naturaleza: "ingreso", activa: true },
  { id: "consalud", categoria_id: "a-ingresos-clientes", nombre: "CONSALUD", naturaleza: "ingreso", activa: true },
  { id: "copec", categoria_id: "a-ingresos-clientes", nombre: "COPEC", naturaleza: "ingreso", activa: true },
  { id: "dfsi", categoria_id: "a-ingresos-clientes", nombre: "DFSI", naturaleza: "ingreso", activa: true },
  { id: "division-andina", categoria_id: "a-ingresos-clientes", nombre: "DIVISIÓN ANDINA", naturaleza: "ingreso", activa: true },
  { id: "division-salvador", categoria_id: "a-ingresos-clientes", nombre: "DIVISIÓN SALVADOR", naturaleza: "ingreso", activa: true },
  { id: "duoc-uc", categoria_id: "a-ingresos-clientes", nombre: "DUOC UC", naturaleza: "ingreso", activa: true },
  { id: "echeverria-izquierdo", categoria_id: "a-ingresos-clientes", nombre: "ECHEVERRÍA IZQUIERDO", naturaleza: "ingreso", activa: true },
  { id: "ecometales", categoria_id: "a-ingresos-clientes", nombre: "ECOMETALES", naturaleza: "ingreso", activa: true },
  { id: "edf", categoria_id: "a-ingresos-clientes", nombre: "EDF", naturaleza: "ingreso", activa: true },
  { id: "egt", categoria_id: "a-ingresos-clientes", nombre: "EGT", naturaleza: "ingreso", activa: true },
  { id: "el-mercurio", categoria_id: "a-ingresos-clientes", nombre: "EL MERCURIO", naturaleza: "ingreso", activa: true },
  { id: "emin", categoria_id: "a-ingresos-clientes", nombre: "EMIN", naturaleza: "ingreso", activa: true },
  { id: "empresas-demaria", categoria_id: "a-ingresos-clientes", nombre: "EMPRESAS DEMARIA", naturaleza: "ingreso", activa: true },
  { id: "empresas-salcobrand", categoria_id: "a-ingresos-clientes", nombre: "EMPRESAS SALCOBRAND", naturaleza: "ingreso", activa: true },
  { id: "empresas-sb", categoria_id: "a-ingresos-clientes", nombre: "EMPRESAS SB", naturaleza: "ingreso", activa: true },
  { id: "empresas-socovesa", categoria_id: "a-ingresos-clientes", nombre: "EMPRESAS SOCOVESA", naturaleza: "ingreso", activa: true },
  { id: "enap", categoria_id: "a-ingresos-clientes", nombre: "ENAP", naturaleza: "ingreso", activa: true },
  { id: "energia-rio-claro", categoria_id: "a-ingresos-clientes", nombre: "ENERGÍA RÍO CLARO", naturaleza: "ingreso", activa: true },
  { id: "entel", categoria_id: "a-ingresos-clientes", nombre: "ENTEL", naturaleza: "ingreso", activa: true },
  { id: "enthalpy", categoria_id: "a-ingresos-clientes", nombre: "ENTHALPY", naturaleza: "ingreso", activa: true },
  { id: "essbio", categoria_id: "a-ingresos-clientes", nombre: "ESSBIO", naturaleza: "ingreso", activa: true },
  { id: "essilorluxottica", categoria_id: "a-ingresos-clientes", nombre: "ESSILORLUXOTTICA", naturaleza: "ingreso", activa: true },
  { id: "essity", categoria_id: "a-ingresos-clientes", nombre: "ESSITY", naturaleza: "ingreso", activa: true },
  { id: "esval", categoria_id: "a-ingresos-clientes", nombre: "ESVAL", naturaleza: "ingreso", activa: true },
  { id: "evol", categoria_id: "a-ingresos-clientes", nombre: "EVOL", naturaleza: "ingreso", activa: true },
  { id: "falabella", categoria_id: "a-ingresos-clientes", nombre: "FALABELLA", naturaleza: "ingreso", activa: true },
  { id: "fedefruta", categoria_id: "a-ingresos-clientes", nombre: "FEDEFRUTA", naturaleza: "ingreso", activa: true },
  { id: "ferradanehme", categoria_id: "a-ingresos-clientes", nombre: "FERRADANEHME", naturaleza: "ingreso", activa: true },
  { id: "finix", categoria_id: "a-ingresos-clientes", nombre: "FINIX", naturaleza: "ingreso", activa: true },
  { id: "fundacion-belen-educa", categoria_id: "a-ingresos-clientes", nombre: "FUNDACIÓN BELEN EDUCA", naturaleza: "ingreso", activa: true },
  { id: "fundacion-gantz", categoria_id: "a-ingresos-clientes", nombre: "FUNDACION GANTZ", naturaleza: "ingreso", activa: true },
  { id: "fundacion-nuestros-hijos", categoria_id: "a-ingresos-clientes", nombre: "FUNDACIÓN NUESTROS HIJOS", naturaleza: "ingreso", activa: true },
  { id: "furoiani", categoria_id: "a-ingresos-clientes", nombre: "FUROIANI", naturaleza: "ingreso", activa: true },
  { id: "goldfield", categoria_id: "a-ingresos-clientes", nombre: "GOLDFIELD", naturaleza: "ingreso", activa: true },
  { id: "grupo-rcd", categoria_id: "a-ingresos-clientes", nombre: "GRUPO RCD", naturaleza: "ingreso", activa: true },
  { id: "grupo-security", categoria_id: "a-ingresos-clientes", nombre: "GRUPO SECURITY", naturaleza: "ingreso", activa: true },
  { id: "grylan", categoria_id: "a-ingresos-clientes", nombre: "GRYLAN", naturaleza: "ingreso", activa: true },
  { id: "gtd", categoria_id: "a-ingresos-clientes", nombre: "GTD", naturaleza: "ingreso", activa: true },
  { id: "hotel-talbot", categoria_id: "a-ingresos-clientes", nombre: "HOTEL TALBOT", naturaleza: "ingreso", activa: true },
  { id: "iconstruye", categoria_id: "a-ingresos-clientes", nombre: "ICONSTRUYE", naturaleza: "ingreso", activa: true },
  { id: "ieside", categoria_id: "a-ingresos-clientes", nombre: "IESIDE", naturaleza: "ingreso", activa: true },
  { id: "iff", categoria_id: "a-ingresos-clientes", nombre: "IFF", naturaleza: "ingreso", activa: true },
  { id: "inchcape", categoria_id: "a-ingresos-clientes", nombre: "INCHCAPE", naturaleza: "ingreso", activa: true },
  { id: "irade", categoria_id: "a-ingresos-clientes", nombre: "IRADE", naturaleza: "ingreso", activa: true },
  { id: "knauf", categoria_id: "a-ingresos-clientes", nombre: "KNAUF", naturaleza: "ingreso", activa: true },
  { id: "komatsu", categoria_id: "a-ingresos-clientes", nombre: "KOMATSU", naturaleza: "ingreso", activa: true },
  { id: "kpmg-chile", categoria_id: "a-ingresos-clientes", nombre: "KPMG CHILE", naturaleza: "ingreso", activa: true },
  { id: "kyndryl", categoria_id: "a-ingresos-clientes", nombre: "KYNDRYL", naturaleza: "ingreso", activa: true },
  { id: "laad", categoria_id: "a-ingresos-clientes", nombre: "LAAD", naturaleza: "ingreso", activa: true },
  { id: "laboratorio-janssen", categoria_id: "a-ingresos-clientes", nombre: "LABORATORIO JANSSEN", naturaleza: "ingreso", activa: true },
  { id: "laboratorios-saval-s-a", categoria_id: "a-ingresos-clientes", nombre: "LABORATORIOS SAVAL S.A.", naturaleza: "ingreso", activa: true },
  { id: "larrain-vial", categoria_id: "a-ingresos-clientes", nombre: "LARRAÍN VIAL", naturaleza: "ingreso", activa: true },
  { id: "mall-plaza", categoria_id: "a-ingresos-clientes", nombre: "MALL PLAZA", naturaleza: "ingreso", activa: true },
  { id: "mas-analytics", categoria_id: "a-ingresos-clientes", nombre: "MAS ANALYTICS", naturaleza: "ingreso", activa: true },
  { id: "mas-errazuriz", categoria_id: "a-ingresos-clientes", nombre: "MAS ERRAZURIZ", naturaleza: "ingreso", activa: true },
  { id: "masisa", categoria_id: "a-ingresos-clientes", nombre: "MASISA", naturaleza: "ingreso", activa: true },
  { id: "metagroup", categoria_id: "a-ingresos-clientes", nombre: "METAGROUP", naturaleza: "ingreso", activa: true },
  { id: "metlife", categoria_id: "a-ingresos-clientes", nombre: "METLIFE", naturaleza: "ingreso", activa: true },
  { id: "metso-chile", categoria_id: "a-ingresos-clientes", nombre: "METSO CHILE", naturaleza: "ingreso", activa: true },
  { id: "minera-florida", categoria_id: "a-ingresos-clientes", nombre: "MINERA FLORIDA", naturaleza: "ingreso", activa: true },
  { id: "minsait-indra", categoria_id: "a-ingresos-clientes", nombre: "MINSAIT INDRA", naturaleza: "ingreso", activa: true },
  { id: "mitsui-auto-finance", categoria_id: "a-ingresos-clientes", nombre: "MITSUI AUTO FINANCE", naturaleza: "ingreso", activa: true },
  { id: "molymet", categoria_id: "a-ingresos-clientes", nombre: "MOLYMET", naturaleza: "ingreso", activa: true },
  { id: "monarch", categoria_id: "a-ingresos-clientes", nombre: "MONARCH", naturaleza: "ingreso", activa: true },
  { id: "mts", categoria_id: "a-ingresos-clientes", nombre: "MTS", naturaleza: "ingreso", activa: true },
  { id: "mutual-de-seguridad", categoria_id: "a-ingresos-clientes", nombre: "MUTUAL DE SEGURIDAD", naturaleza: "ingreso", activa: true },
  { id: "nestle", categoria_id: "a-ingresos-clientes", nombre: "NESTLE", naturaleza: "ingreso", activa: true },
  { id: "nttdata", categoria_id: "a-ingresos-clientes", nombre: "NTTDATA", naturaleza: "ingreso", activa: true },
  { id: "ogilvy", categoria_id: "a-ingresos-clientes", nombre: "Ogilvy", naturaleza: "ingreso", activa: true },
  { id: "ohl", categoria_id: "a-ingresos-clientes", nombre: "OHL", naturaleza: "ingreso", activa: true },
  { id: "old-navy", categoria_id: "a-ingresos-clientes", nombre: "OLD NAVY", naturaleza: "ingreso", activa: true },
  { id: "opia-marketing", categoria_id: "a-ingresos-clientes", nombre: "OPIA MARKETING", naturaleza: "ingreso", activa: true },
  { id: "oracle", categoria_id: "a-ingresos-clientes", nombre: "ORACLE", naturaleza: "ingreso", activa: true },
  { id: "oxiquim", categoria_id: "a-ingresos-clientes", nombre: "OXIQUIM", naturaleza: "ingreso", activa: true },
  { id: "papelera-lo-izquierdo", categoria_id: "a-ingresos-clientes", nombre: "PAPELERA LO IZQUIERDO", naturaleza: "ingreso", activa: true },
  { id: "parque-arauco", categoria_id: "a-ingresos-clientes", nombre: "PARQUE ARAUCO", naturaleza: "ingreso", activa: true },
  { id: "pflp", categoria_id: "a-ingresos-clientes", nombre: "PFLP", naturaleza: "ingreso", activa: true },
  { id: "pisquera-de-chile", categoria_id: "a-ingresos-clientes", nombre: "PISQUERA DE CHILE", naturaleza: "ingreso", activa: true },
  { id: "plaza-maule", categoria_id: "a-ingresos-clientes", nombre: "PLAZA MAULE", naturaleza: "ingreso", activa: true },
  { id: "porsche", categoria_id: "a-ingresos-clientes", nombre: "PORSCHE", naturaleza: "ingreso", activa: true },
  { id: "pragmaxion", categoria_id: "a-ingresos-clientes", nombre: "PRAGMAXION", naturaleza: "ingreso", activa: true },
  { id: "prestigio", categoria_id: "a-ingresos-clientes", nombre: "PRESTIGIO", naturaleza: "ingreso", activa: true },
  { id: "promigas", categoria_id: "a-ingresos-clientes", nombre: "PROMIGAS", naturaleza: "ingreso", activa: true },
  { id: "pronto-espacio", categoria_id: "a-ingresos-clientes", nombre: "PRONTO ESPACIO", naturaleza: "ingreso", activa: true },
  { id: "prosegur", categoria_id: "a-ingresos-clientes", nombre: "PROSEGUR", naturaleza: "ingreso", activa: true },
  { id: "pucobre", categoria_id: "a-ingresos-clientes", nombre: "PUCOBRE", naturaleza: "ingreso", activa: true },
  { id: "quimica-latinoamericana", categoria_id: "a-ingresos-clientes", nombre: "QUÍMICA LATINOAMERICANA", naturaleza: "ingreso", activa: true },
  { id: "red-igualdad", categoria_id: "a-ingresos-clientes", nombre: "RED IGUALDAD", naturaleza: "ingreso", activa: true },
  { id: "ride", categoria_id: "a-ingresos-clientes", nombre: "RIDE", naturaleza: "ingreso", activa: true },
  { id: "roche", categoria_id: "a-ingresos-clientes", nombre: "ROCHE", naturaleza: "ingreso", activa: true },
  { id: "salfa", categoria_id: "a-ingresos-clientes", nombre: "SALFA", naturaleza: "ingreso", activa: true },
  { id: "scotiabank", categoria_id: "a-ingresos-clientes", nombre: "SCOTIABANK", naturaleza: "ingreso", activa: true },
  { id: "scretting", categoria_id: "a-ingresos-clientes", nombre: "SCRETTING", naturaleza: "ingreso", activa: true },
  { id: "servicio-civil", categoria_id: "a-ingresos-clientes", nombre: "SERVICIO CIVIL", naturaleza: "ingreso", activa: true },
  { id: "simon-de-cirene", categoria_id: "a-ingresos-clientes", nombre: "SIMON DE CIRENE", naturaleza: "ingreso", activa: true },
  { id: "sinacofi", categoria_id: "a-ingresos-clientes", nombre: "SINACOFI", naturaleza: "ingreso", activa: true },
  { id: "sk", categoria_id: "a-ingresos-clientes", nombre: "SK", naturaleza: "ingreso", activa: true },
  { id: "sky-airlines", categoria_id: "a-ingresos-clientes", nombre: "SKY AIRLINES", naturaleza: "ingreso", activa: true },
  { id: "softys", categoria_id: "a-ingresos-clientes", nombre: "SOFTYS", naturaleza: "ingreso", activa: true },
  { id: "southbridge", categoria_id: "a-ingresos-clientes", nombre: "SOUTHBRIDGE", naturaleza: "ingreso", activa: true },
  { id: "starken", categoria_id: "a-ingresos-clientes", nombre: "STARKEN", naturaleza: "ingreso", activa: true },
  { id: "statkraft", categoria_id: "a-ingresos-clientes", nombre: "STATKRAFT", naturaleza: "ingreso", activa: true },
  { id: "sura", categoria_id: "a-ingresos-clientes", nombre: "SURA", naturaleza: "ingreso", activa: true },
  { id: "systep", categoria_id: "a-ingresos-clientes", nombre: "SYSTEP", naturaleza: "ingreso", activa: true },
  { id: "tanner", categoria_id: "a-ingresos-clientes", nombre: "TANNER", naturaleza: "ingreso", activa: true },
  { id: "teck", categoria_id: "a-ingresos-clientes", nombre: "TECK", naturaleza: "ingreso", activa: true },
  { id: "testcloud", categoria_id: "a-ingresos-clientes", nombre: "TESTCLOUD", naturaleza: "ingreso", activa: true },
  { id: "tgr", categoria_id: "a-ingresos-clientes", nombre: "TGR", naturaleza: "ingreso", activa: true },
  { id: "the-coca-cola-company", categoria_id: "a-ingresos-clientes", nombre: "THE COCA-COLA COMPANY", naturaleza: "ingreso", activa: true },
  { id: "tigre-ads", categoria_id: "a-ingresos-clientes", nombre: "TIGRE/ADS", naturaleza: "ingreso", activa: true },
  { id: "timining", categoria_id: "a-ingresos-clientes", nombre: "TIMINING", naturaleza: "ingreso", activa: true },
  { id: "toctoc", categoria_id: "a-ingresos-clientes", nombre: "TOCTOC", naturaleza: "ingreso", activa: true },
  { id: "tottus", categoria_id: "a-ingresos-clientes", nombre: "TOTTUS", naturaleza: "ingreso", activa: true },
  { id: "transelec", categoria_id: "a-ingresos-clientes", nombre: "TRANSELEC", naturaleza: "ingreso", activa: true },
  { id: "trendy", categoria_id: "a-ingresos-clientes", nombre: "TRENDY", naturaleza: "ingreso", activa: true },
  { id: "tres-montes", categoria_id: "a-ingresos-clientes", nombre: "TRES MONTES", naturaleza: "ingreso", activa: true },
  { id: "triciclos", categoria_id: "a-ingresos-clientes", nombre: "TRICICLOS", naturaleza: "ingreso", activa: true },
  { id: "uai", categoria_id: "a-ingresos-clientes", nombre: "UAI", naturaleza: "ingreso", activa: true },
  { id: "universidad-adolfo-ibanez", categoria_id: "a-ingresos-clientes", nombre: "UNIVERSIDAD ADOLFO IBAÑEZ", naturaleza: "ingreso", activa: true },
  { id: "universidad-de-atacama", categoria_id: "a-ingresos-clientes", nombre: "UNIVERSIDAD DE ATACAMA", naturaleza: "ingreso", activa: true },
  { id: "universidad-san-sebastian", categoria_id: "a-ingresos-clientes", nombre: "UNIVERSIDAD SAN SEBASTIAN", naturaleza: "ingreso", activa: true },
  { id: "uno-salud", categoria_id: "a-ingresos-clientes", nombre: "UNO SALUD", naturaleza: "ingreso", activa: true },
  { id: "vantaz", categoria_id: "a-ingresos-clientes", nombre: "VANTAZ", naturaleza: "ingreso", activa: true },
  { id: "vida-camara", categoria_id: "a-ingresos-clientes", nombre: "VIDA CAMARA", naturaleza: "ingreso", activa: true },
  { id: "walmart", categoria_id: "a-ingresos-clientes", nombre: "WALMART", naturaleza: "ingreso", activa: true },
  { id: "wec", categoria_id: "a-ingresos-clientes", nombre: "WEC", naturaleza: "ingreso", activa: true },
  { id: "zurich", categoria_id: "a-ingresos-clientes", nombre: "ZURICH", naturaleza: "ingreso", activa: true },
  { id: "otros-ingresos", categoria_id: "b-otros-ingresos", nombre: "Otros ingresos", naturaleza: "ingreso", activa: true },
  { id: "prestamos-bancarios", categoria_id: "b-otros-ingresos", nombre: "Prestamos bancarios", naturaleza: "ingreso", activa: true },
  { id: "prestamos-relacionadas", categoria_id: "b-otros-ingresos", nombre: "Prestamos relacionadas", naturaleza: "ingreso", activa: true },
  { id: "utilidades-colombia", categoria_id: "b-otros-ingresos", nombre: "Utilidades Colombia", naturaleza: "ingreso", activa: true },
  { id: "utilidades-peru", categoria_id: "b-otros-ingresos", nombre: "Utilidades Perú", naturaleza: "ingreso", activa: true },
  { id: "conferencias", categoria_id: "1-costo-de-venta", nombre: "Conferencias", naturaleza: "operativo", activa: true },
  { id: "costos-directos-consultoria", categoria_id: "1-costo-de-venta", nombre: "Costos directos consultoría", naturaleza: "operativo", activa: true },
  { id: "costos-directos-consultoria-equipa", categoria_id: "1-costo-de-venta", nombre: "Costos directos consultoría - Equipamiento tecnológico Salvador", naturaleza: "operativo", activa: true },
  { id: "costos-directos-consultoria-examen", categoria_id: "1-costo-de-venta", nombre: "Costos directos consultoría - Exámenes y certificaciones Salvador", naturaleza: "operativo", activa: true },
  { id: "costos-directos-consultoria-logist", categoria_id: "1-costo-de-venta", nombre: "Costos directos consultoría - Logística Salvador", naturaleza: "operativo", activa: true },
  { id: "costos-directos-consultoria-materi", categoria_id: "1-costo-de-venta", nombre: "Costos directos consultoría - Materiales Salvador", naturaleza: "operativo", activa: true },
  { id: "distribucion-de-margen", categoria_id: "1-costo-de-venta", nombre: "Distribución de margen", naturaleza: "operativo", activa: true },
  { id: "generacion-de-contenido", categoria_id: "1-costo-de-venta", nombre: "Generación de contenido", naturaleza: "operativo", activa: true },
  { id: "horas", categoria_id: "1-costo-de-venta", nombre: "Horas", naturaleza: "operativo", activa: true },
  { id: "ingreso-minimo-asegurado", categoria_id: "1-costo-de-venta", nombre: "Ingreso mínimo asegurado", naturaleza: "operativo", activa: true },
  { id: "jefaturas", categoria_id: "1-costo-de-venta", nombre: "Jefaturas", naturaleza: "operativo", activa: true },
  { id: "actividades-aprendizaje-organizaci", categoria_id: "1-desarrollo-organizaciona", nombre: "Actividades aprendizaje organizacional", naturaleza: "inversion", activa: true },
  { id: "asesoria-proy-desarrollo-interno", categoria_id: "1-desarrollo-organizaciona", nombre: "AsesorÍa Proy. Desarrollo Interno", naturaleza: "inversion", activa: true },
  { id: "asesoria-proyectos-probono", categoria_id: "1-desarrollo-organizaciona", nombre: "Asesoría proyectos Probono", naturaleza: "inversion", activa: true },
  { id: "capacitacion-consultores", categoria_id: "1-desarrollo-organizaciona", nombre: "Capacitación Consultores", naturaleza: "operativo", activa: true },
  { id: "coalicion-de-cambio", categoria_id: "1-desarrollo-organizaciona", nombre: "Coalición de cambio", naturaleza: "inversion", activa: true },
  { id: "consultoria-y-gestion-de-proyectos", categoria_id: "1-desarrollo-organizaciona", nombre: "Consultoría y gestión de proyectos", naturaleza: "inversion", activa: true },
  { id: "direccion-ejecutiva", categoria_id: "1-desarrollo-organizaciona", nombre: "Dirección Ejecutiva", naturaleza: "inversion", activa: true },
  { id: "proyecto-formacion", categoria_id: "1-desarrollo-organizaciona", nombre: "Proyecto formación", naturaleza: "inversion", activa: true },
  { id: "reparto-de-utilidades-anuales", categoria_id: "1-desarrollo-organizaciona", nombre: "Reparto de utilidades anuales", naturaleza: "inversion", activa: true },
  { id: "arriendo-oficina", categoria_id: "2-gastos-administracion", nombre: "Arriendo oficina", naturaleza: "operativo", activa: true },
  { id: "asesoria-contable", categoria_id: "2-gastos-administracion", nombre: "Asesoría contable", naturaleza: "operativo", activa: true },
  { id: "beneficios-personas", categoria_id: "2-gastos-administracion", nombre: "Beneficios personas", naturaleza: "operativo", activa: true },
  { id: "caja-chica", categoria_id: "2-gastos-administracion", nombre: "Caja chica", naturaleza: "operativo", activa: true },
  { id: "certificaciones", categoria_id: "2-gastos-administracion", nombre: "Certificaciones", naturaleza: "inversion", activa: true },
  { id: "contribuciones", categoria_id: "2-gastos-administracion", nombre: "Contribuciones", naturaleza: "operativo", activa: true },
  { id: "equipamiento-oficina", categoria_id: "2-gastos-administracion", nombre: "Equipamiento oficina", naturaleza: "inversion", activa: true },
  { id: "gastos-comunes", categoria_id: "2-gastos-administracion", nombre: "Gastos comunes", naturaleza: "operativo", activa: true },
  { id: "gastos-de-representacion", categoria_id: "2-gastos-administracion", nombre: "Gastos de representación", naturaleza: "operativo", activa: true },
  { id: "gastos-legales", categoria_id: "2-gastos-administracion", nombre: "Gastos legales", naturaleza: "operativo", activa: true },
  { id: "insumos-oficina", categoria_id: "2-gastos-administracion", nombre: "Insumos oficina", naturaleza: "operativo", activa: true },
  { id: "jornadas-y-eventos-organizacion", categoria_id: "2-gastos-administracion", nombre: "Jornadas y eventos organizacion", naturaleza: "operativo", activa: true },
  { id: "offsite-internacional", categoria_id: "2-gastos-administracion", nombre: "Offsite internacional", naturaleza: "operativo", activa: true },
  { id: "mant-y-reparacion-oficina", categoria_id: "2-gastos-administracion", nombre: "Mant. y Reparación oficina", naturaleza: "operativo", activa: true },
  { id: "patente-comercial", categoria_id: "2-gastos-administracion", nombre: "Patente comercial", naturaleza: "operativo", activa: true },
  { id: "telefonia-e-internet", categoria_id: "2-gastos-administracion", nombre: "Telefonía e internet", naturaleza: "operativo", activa: true },
  { id: "agencia-comunicaciones", categoria_id: "2-0-comercial-y-marketing", nombre: "Agencia comunicaciones", naturaleza: "inversion", activa: true },
  { id: "alianzas-estudios-y-relacionamient", categoria_id: "2-0-comercial-y-marketing", nombre: "Alianzas, estudios y relacionamiento", naturaleza: "inversion", activa: true },
  { id: "asistencia-a-eventos", categoria_id: "2-0-comercial-y-marketing", nombre: "Asistencia a eventos", naturaleza: "operativo", activa: true },
  { id: "estudios-publicos", categoria_id: "2-0-comercial-y-marketing", nombre: "Estudios públicos", naturaleza: "inversion", activa: true },
  { id: "eventos-propios", categoria_id: "2-0-comercial-y-marketing", nombre: "Eventos propios", naturaleza: "inversion", activa: true },
  { id: "gastos-de-marketing", categoria_id: "2-0-comercial-y-marketing", nombre: "Gastos de marketing", naturaleza: "operativo", activa: true },
  { id: "marketing-digital", categoria_id: "2-0-comercial-y-marketing", nombre: "Marketing digital", naturaleza: "inversion", activa: true },
  { id: "medios-digitales", categoria_id: "2-0-comercial-y-marketing", nombre: "Medios digitales", naturaleza: "operativo", activa: true },
  { id: "pagina-web", categoria_id: "2-0-comercial-y-marketing", nombre: "Página web", naturaleza: "inversion", activa: true },
  { id: "branding-y-merchandising", categoria_id: "2-1-posicionamiento-nueva", nombre: "Branding y merchandising", naturaleza: "inversion", activa: true },
  { id: "difusion-nueva-marca", categoria_id: "2-1-posicionamiento-nueva", nombre: "Difusión nueva marca", naturaleza: "inversion", activa: true },
  { id: "nueva-marca-organizacional", categoria_id: "2-1-posicionamiento-nueva", nombre: "Nueva marca organizacional", naturaleza: "inversion", activa: true },
  { id: "2-1-posicionamiento-nueva-pagina-web", categoria_id: "2-1-posicionamiento-nueva", nombre: "Pagina web", naturaleza: "inversion", activa: true },
  { id: "registro-legales-nueva-marca", categoria_id: "2-1-posicionamiento-nueva", nombre: "Registro legales nueva marca", naturaleza: "inversion", activa: true },
  { id: "garantias", categoria_id: "2-2-compra-activos", nombre: "Garantías", naturaleza: "inversion", activa: true },
  { id: "infraestructura", categoria_id: "2-2-compra-activos", nombre: "Infraestructura", naturaleza: "inversion", activa: true },
  { id: "legales-y-puesta-en-marcha", categoria_id: "2-2-compra-activos", nombre: "Legales y puesta en marcha", naturaleza: "inversion", activa: true },
  { id: "muebles-y-enseres", categoria_id: "2-2-compra-activos", nombre: "Muebles y enseres", naturaleza: "inversion", activa: true },
  { id: "propiedades-oficina", categoria_id: "2-2-compra-activos", nombre: "Propiedades (Oficina)", naturaleza: "inversion", activa: true },
  { id: "gastos-sistemas-digitales", categoria_id: "2-3-gastos-sistemas-digita", nombre: "Gastos sistemas digitales", naturaleza: "operativo", activa: true },
  { id: "sistemas-analitica-avanzada-ia-y-r", categoria_id: "2-3-gastos-sistemas-digita", nombre: "Sistemas Analítica avanzada, IA y Relac.", naturaleza: "operativo", activa: true },
  { id: "sistemas-diseno", categoria_id: "2-3-gastos-sistemas-digita", nombre: "Sistemas Diseño", naturaleza: "inversion", activa: true },
  { id: "sistemas-operaciones", categoria_id: "2-3-gastos-sistemas-digita", nombre: "Sistemas Operaciones", naturaleza: "operativo", activa: true },
  { id: "sistemas-operaciones-y-finanzas", categoria_id: "2-3-gastos-sistemas-digita", nombre: "Sistemas Operaciones y Finanzas", naturaleza: "operativo", activa: true },
  { id: "equipos-computacionales", categoria_id: "2-4-equipos-computacionale", nombre: "Equipos Computacionales", naturaleza: "inversion", activa: true },
  { id: "mantenimiento-equipos", categoria_id: "2-4-equipos-computacionale", nombre: "Mantenimiento Equipos", naturaleza: "operativo", activa: true },
  { id: "capacitacion-del-personal", categoria_id: "3-recursos-humanos", nombre: "Capacitación del personal", naturaleza: "inversion", activa: true },
  { id: "finiquitos", categoria_id: "3-recursos-humanos", nombre: "Finiquitos", naturaleza: "operativo", activa: true },
  { id: "imposiciones", categoria_id: "3-recursos-humanos", nombre: "Imposiciones", naturaleza: "operativo", activa: true },
  { id: "jornadas-y-eventos-equipo-interno", categoria_id: "3-recursos-humanos", nombre: "Jornadas y eventos equipo interno", naturaleza: "operativo", activa: true },
  { id: "servicios-externos-rr-hh", categoria_id: "3-recursos-humanos", nombre: "Servicios externos RR.HH", naturaleza: "operativo", activa: true },
  { id: "sueldos", categoria_id: "3-recursos-humanos", nombre: "Sueldos", naturaleza: "operativo", activa: true },
  { id: "impuesto-a-la-renta", categoria_id: "4-impuestos", nombre: "Impuesto a la renta", naturaleza: "operativo", activa: true },
  { id: "iva-compras", categoria_id: "4-impuestos", nombre: "IVA compras", naturaleza: "operativo", activa: true },
  { id: "iva-mensual", categoria_id: "4-impuestos", nombre: "IVA mensual", naturaleza: "operativo", activa: true },
  { id: "retencion-bhe", categoria_id: "4-impuestos", nombre: "Retención BHE", naturaleza: "operativo", activa: true },
  { id: "comisiones-bancarias", categoria_id: "5-bancos", nombre: "Comisiones bancarias", naturaleza: "operativo", activa: true },
  { id: "tarjeta-de-credito", categoria_id: "5-bancos", nombre: "Tarjeta de credito", naturaleza: "operativo", activa: true },
  { id: "traspaso-entre-empresas", categoria_id: "5-bancos", nombre: "Traspaso entre empresas", naturaleza: "operativo", activa: true },
  { id: "prestamos-bancarios-pago", categoria_id: "6-prestamos-bancarios", nombre: "Prestamos bancarios (pago)", naturaleza: "operativo", activa: true },
  { id: "depositos-a-plazo", categoria_id: "7-inversiones", nombre: "Depositos a plazo", naturaleza: "operativo", activa: true },
  { id: "firmex", categoria_id: "7-inversiones", nombre: "Firmex", naturaleza: "operativo", activa: true },
  { id: "fondos-mutuos", categoria_id: "7-inversiones", nombre: "Fondos mutuos", naturaleza: "operativo", activa: true },
  { id: "invexor", categoria_id: "7-inversiones", nombre: "Invexor", naturaleza: "operativo", activa: true },
  { id: "poliglota", categoria_id: "7-inversiones", nombre: "Poliglota", naturaleza: "operativo", activa: true },
  { id: "adapsys-miami", categoria_id: "8-relacionados-y-socios", nombre: "Adapsys Miami", naturaleza: "operativo", activa: true },
  { id: "cuenta-corriente-peru-chile", categoria_id: "8-relacionados-y-socios", nombre: "Cuenta corriente Perú-Chile", naturaleza: "operativo", activa: true },
  { id: "participacion-comite", categoria_id: "8-relacionados-y-socios", nombre: "Participación Comité", naturaleza: "operativo", activa: true },
  { id: "prestamos-socios", categoria_id: "8-relacionados-y-socios", nombre: "Préstamos socios", naturaleza: "operativo", activa: true },
  { id: "retiros-socios", categoria_id: "8-relacionados-y-socios", nombre: "Retiros socios", naturaleza: "operativo", activa: true },
];
